INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES('Ação');
INSERT INTO tb_genre (name) VALUES('Aventura');
INSERT INTO tb_genre (name) VALUES('Comédia');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O PROTETOR', '2', 2018, 'https://br.web.img2.acsta.net/c_310_420/pictures/18/06/19/13/51/0647704.jpg', 'Massachusetts, Estados Unidos. Robert McCall (Denzel Washington) agora trabalha como motorista, ajudando pessoas que enfrentam dificuldades decorrentes de injustiças. Quando sua amiga Susan Plummer (Melissa Leo) é morta durante a investigação de um assassinato na Bélgica, ele decide sair do anonimato e encontrar seu antigo parceiro, Dave (Pedro Pascal), no intuito de encontrar pistas sobre o autor do crime.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('SEM REMORSO', '', 2021, 'https://br.web.img3.acsta.net/c_310_420/pictures/21/04/12/16/00/4386818.jpg', 'Sem Remorso conta a história de John Kelly (Michael B. Jordan), um oficial de elite da Marinha. Quando um esquadrão de soldados russos mata sua esposa grávida em retaliação ao seu papel em uma operação ultrassecreta, ele persegue os assassinos a todo custo. Unindo forças com um companheira da marinha (Jodie Turner-Smith) e um sombrio agente da CIA (Jamie Bell), a missão de Kelly involuntariamente expõe uma conspiração secreta que ameaça envolver os EUA e a Rússia em uma grande guerra. Dividido entre a honra pessoal e a lealdade ao seu país, Kelly deve lutar sem nenhum remorso contra seus inimigos se quiser evitar um desastre e expor as figuras poderosas por trás da conspiração. Inspirado no livro de Tom Clancy, parte do universo de Jack Ryan.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes & Furiosos', 'Hobbs & Shaw', 2019, 'https://cdn.tlc-massive.com/shain/v1/dataservice/ResizeImage/$value?Format=%27jpg%27&Quality=85&ImageId=%27209120.jpg%27&ImageUrl=%27209120.jpg%27&EntityType=%27Item%27&EntityId=%2718150%27&device=web_browser&subscriptions=Anonymous&Width=360&Height=540', 'O agente Luke Hobbs (Dwayne Johnson) e o ex-militar Deckard Shaw (Jason Statham) nunca se deram bem, mas uma ameaça ao planeta faz com que os caminhos da dupla se cruzem. Brixton (Idris Elba), um mercenário geneticamente modificado, está atrás da agente Hattie (Vanessa Kirby), que está com uma arma química poderosíssima. Para evitar uma catástrofe mundial, Hobbs e Shaw usarão toda a habilidade que têm, além de contar com a ajuda das poderosas Queenie (Helen Mirren) e Madame M (Eiza Gonzáles).', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('TENET', '', 2020, 'https://br.web.img3.acsta.net/c_310_420/pictures/20/05/19/20/45/1889845.jpg', 'Um agente da CIA conhecido como O Protagonista (John David Washington) é recrutado por uma organização misteriosa, chamada Tenet, para participar de uma missão de escala global. Eles precisam impedir que Andrei Sator (Kenneth Branagh), um renegado oligarca russo com meios de se comunicar com o futuro, inicie a Terceira Guerra Mundial. A organização está em posse de uma arma de fogo que consegue fazer o tempo correr ao contrário, acreditando que o objeto veio do futuro. Com essa habilidade em mãos, O Protagonista precisará usá-la como forma de se opor à ameaça que está por vir, impedindo que os planos de Sator se concretizem.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('FROZEN', 'UMA AVENTURA CONGELANTE', 2014, 'https://br.web.img3.acsta.net/c_310_420/pictures/210/461/21046189_20131002174340886.jpg', 'A caçula Anna (Kristen Bell/Gabi Porto) adora sua irmã Elsa (Idina Menzel/Taryn Szpilman), mas um acidente envolvendo os poderes especiais da mais velha, durante a infância, fez com que os pais as mantivessem afastadas. Após a morte deles, as duas cresceram isoladas no castelo da família, até o dia em que Elsa deveria assumir o reinado de Arendell. Com o reencontro das duas, um novo acidente acontece e ela decide partir para sempre e se isolar do mundo, deixando todos para trás e provocando o congelamento do reino. É quando Anna decide se aventurar pelas montanhas de gelo para encontrar a irmã e acabar com o frio.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('UMA AVENTURA LEGO', '', 2014, 'https://br.web.img3.acsta.net/c_310_420/pictures/13/12/02/20/59/515779.jpg', 'Emmet (Chris Pratt) é um Lego comum, até o dia em que é confundido com o Master Builder, o grande criador deste mundo de brinquedo, por ter encontrado a famosa peça de resistência. Este peça, procurada por todos há séculos, seria capaz de desarmar uma poderosa máquina criada pelo presidente do país, o perverso Sr. Negócios, que pretende colar todas as peças e impedir as mudanças no sistema. Mesmo sem ter grandes habilidades como criador, Emmet gosta de ser considerado um Lego especial, e faz de tudo para merecer a confiança de seus amigos, que incluem a rebelde Mega Estilo, o sábio Vitrúvius, e o gato-unicórnio UniKitty.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('DETETIVES DO PRÉDIO AZUL 3', 'UMA AVENTURA NO FIM DO MUNDO', 2021, 'https://br.web.img2.acsta.net/c_310_420/pictures/20/10/29/20/04/5288368.jpg', 'Em Detetives do Prédio Azul 3 - Uma Aventura no Fim do Mundo, Pippo (Pedro Henriques Motta), Bento (Anderson Lima) e Sol (Letícia Braga) se vêem em apuros quando Severino (Ronaldo Reis) encontra um objeto em meio aos escombros de um avião. O que parecia uma inofensiva relíquia era, na verdade, uma das faces do ‘Medalhão de Uzur’, responsável por controlar e manipular toda a magia existente no mundo. Assim que coloca o artefato no pescoço, o porteiro tão querido por todos começa a se transformar em uma figura malígna.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('UMA COMÉDIA NADA ROMÂNTICA', '', 2006, 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/95/11/11/20380530.jpg', 'Julia Jones (Alyson Hannigan) é uma garçonete pouco atraente, que trabalha no restaurante de seu pai. Ela sonha em achar o homem de seus sonhos e se casar, mas tem um sério problema de peso, que lhe impede de deixar uma impressão positiva nas pessoas. Mesmo assim ela o acha e o perde em segundos. Assim, vai até um conselheiro sentimental, que manda fazer uma "lanternagem" nela, o que a transforma numa bela jovem. Ela consegue reencontrar e conquistar Grant Comotuafilha (Adam Campbell), que também se apaixona por ela. Eles não desperdiçam tempo e marcam a data do casamento. Enquanto o dia não chega eles lidam com problemas, como os pais dela querendo se intrometer na sua vida e o confronto de Julia com a ex-noiva de Grant, Andy (Sophie Monk), que quer usar sua sensualidade e beleza para evitar que Grant se case', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A COMÉDIA DIVINA', '', 2017, 'https://br.web.img2.acsta.net/c_310_420/pictures/16/07/05/19/03/413995.jpg', 'Em crise, um programa jornalístico demite uma repórter e em seu lugar contrata Raquel (Mônica Iozzi), jornalista recém-formada, caso do âncora garanhão, Mateus (Dalton Vigh). Incomodada pela convivência com Lucas (Thiago Mendonça), um inconformado ex-namorado que trabalha na produção, ela vê sua carreira decolar graças a um furo: o Diabo (Murilo Rosa) acaba de abrir sua própria igreja na Terra.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Minha Mãe É Uma Peça', '3', 2019, 'https://cdn.tlc-massive.com/shain/v1/dataservice/ResizeImage/$value?Format=%27jpg%27&Quality=85&ImageId=%27208048.jpg%27&ImageUrl=%27208048.jpg%27&EntityType=%27Item%27&EntityId=%2718028%27&device=web_browser&subscriptions=Anonymous&Width=360&Height=540', 'Após ter um piripaque, Dona Hermínia (Paulo Gustavo) recebe duas notícias: Marcelina (Mariana Xavier) está grávida de um cara que mal conhece e Juliano (Rodrigo Pandolfo) está noivo. Sofrendo ao ver que seus filhos já estão formando suas próprias famílias, ela decide focar nos preparativos para o casamento. Com o apoio de sua diarista Waldeia (Samantha Schmütz) e de suas irmãs Iesa (Alexandra Richter) e Lucia Helena (Patricya Travassos), a matriarca terá que driblar a sogra de seu filho, além de lidar com as novas investidas de Carlos Alberto (Herson Capri), seu ex-marido.', 3);

INSERT INTO tb_review (user_id, movie_id, text) VALUES (1, 3, 'Velozes e furiosos é muito top!');
INSERT INTO tb_review (user_id, movie_id, text) VALUES (1, 10, 'Sensacional, dei muita risada rsrs');
